### ISSUE TITLE
Question regarding running sz_cmh.py from poolseq_tk

### ISSUE THREAD

**Issue by orijitghosh** [svm-zhang/poolseq_tk#1]
Hi,
I will like to use the `sz_cmh.py` script to perform a CMH test from a SYNC file and also compute an FDR threshold.
However, I can't figure out the usage of your code. Would you be kind enough to help me through it?
Thank you,
Arijit

**Comment by svm-zhang** [comment]
@orijitghosh, yes, I can help. Please be patient with me if possible :) And apologize for the lack of documentation. 

To run CMH test, we need a count table which is generated by the 'count' command. And the count command requires a pileup file as input. The package cannot handle SYNC file format.

Could I ask is it possible you could run samtools mpileup on each of your pooled BAMs? And we could go from there, one step at a time.

**Comment by orijitghosh** [comment]
@svm-zhang , I already have mpileups. What to do next?
Thanks for your help. Much appreciated.

**Comment by svm-zhang** [comment]
I have been trying to make a local environment setup, because I lost my access to the server on which I developed the package. Could you please first check several things before running it. We need python 2.7 and legacy version of rpy2. May I ask do you have them successfully installed?

If you only have python 3, then I need to update the entire package for it to support python 3.

**Comment by svm-zhang** [comment]
Please re-clone the repo, I just pushed a small patch.

If you had the required environment, lets try the first steps.

Step 1:
`python poolseq_tk.py biallelic -o snp.bi.txt pool_1.pileup`

Could you please show me the first 20 lines of the `snp.bi.txt` file?

**Comment by orijitghosh** [comment]
I have the required environment set up already. But my machine has only 16 GB RAM and my mpileups are more than 25 GB each. I have zipped ones, which are ~4.5 GB each, but I guess those can't be used. I get the following error:
Traceback (most recent call last):
```
  File "/mnt/d/Downloads/Compressed/poolseq_tk-master/poolseq_tk.py", line 367, in <module>
    main()
  File "/mnt/d/Downloads/Compressed/poolseq_tk-master/poolseq_tk.py", line 364, in main
    args.func(args)
  File "/mnt/d/Downloads/Compressed/poolseq_tk-master/sz_biallelic.py", line 8, in run_biallelic
    dPileups = syncPileups(args.pileups)
  File "/mnt/d/Downloads/Compressed/poolseq_tk-master/sz_biallelic.py", line 44, in syncPileups
    for line in fIN:
MemoryError
Killed
```

**Comment by svm-zhang** [comment]
@orijitghosh, this needs me to rewrite quite some code to do it. Do you have time to wait? And would you mind if you could share one of your 25GB pileup with me?

**Comment by orijitghosh** [comment]
@svm-zhang , I will have access to a better machine, it'll take a couple of days. Let me run it there first, rather than bothering you with rewriting codes. I greatly appreciate your help. I will come back to you in a few days. And I will email you about it.
Thank you so much! People like you make the community much better.

**Comment by svm-zhang** [comment]
@orijitghosh, thanks for the heads up. That sounds good. If you still have the problem, let me rewrite. I think the first 3 steps can be merged into one (hopefully). Happy Thanksgiving!
